spring:
  datasource: # H2 DB 설정
#    url: jdbc:mysql://localhost:3306/devblog?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    url: jdbc:mysql://144.24.77.45:3306/devblog?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: devblog
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.